apiVersion: v1
kind: Namespace
metadata:
  name: autoseo-dev
  labels:
    environment: development
    app.kubernetes.io/part-of: autoseo
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoseo-staging
  labels:
    environment: staging
    app.kubernetes.io/part-of: autoseo
---
apiVersion: v1
kind: Namespace
metadata:
  name: autoseo-prod
  labels:
    environment: production
    app.kubernetes.io/part-of: autoseo
